FabManager/urls.py
"""
Definition of urls for FabManager.
"""

from datetime import datetime
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.i18n import i18n_patterns
from app.forms import BootstrapAuthenticationForm
from django.conf.urls.static import static
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
from app import views
from django.contrib.auth import views as auth_views
urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += i18n_patterns(
    url(r'^$', views.home, name='home'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^about$', views.about, name='about'),
    url(r'^Profil$', views.ViewProfil, name='Profil'),
    url(r'^Profil/EditNewsLetter$', views.EditNewsLetter, name='EditNewsLetter'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^Article/(?P<NbPage>\d+)$', views.ViewArticle, name='ViewArticle'),
    url(r'^Projet/AddProjet/$', views.CreationProjet, name='NewProjet'),
    url(r'^Projet/EditProjet/(?P<NbPage>\d+)$', views.EditProjet, name='EditProjet'),
    url(r'^Projet/DeleteProjet/(?P<NbPage>\d+)$', views.DeleteProjet, name='DeleteProjet'),
    url(r'^Projet/(?P<NbPage>\d+)$', views.ViewProjet, name='ViewProjet'),
    url(r'^Atelier/(?P<NbPage>\d+)$', views.ViewAtelier, name='ViewAtelier'),
    url(r'^Atelier/Desinscription/(?P<Action>\d+)/$', views.DesinscriptionAtelier, name='DesinscriptionAtelier'),
    url(r'^Atelier/Inscription/(?P<Action>\d+)/$', views.InscriptionAtelier, name='InscriptionAtelier'),
    url(r'^Machine/(?P<NbPage>\d+)$', views.ViewMachine, name='ViewMachine'),
    url(r'^ListMachine/$', views.ListMachine, name='ListMachine'),
    url(r'^ListMachine/(?P<NbPage>\d+)$', views.ListMachine, name=''),    
    url(r'^ListAtelier/$', views.ListAtelier, name='ListAtelier'),
    url(r'^ListAtelier/(?P<NbPage>\d+)$', views.ListAtelier, name='PListAtelier'),
    url(r'^ListArticle/$', views.ListArticle, name='ListArticle'),
    url(r'^ListArticle/(?P<NbPage>\d+)$', views.ListArticle, name='PListArticle'),
    url(r'^ListProjet/$', views.ListProjet, name='ListProjet'),
    url(r'^Admin/', admin.site.urls , name='AdminPage'),
    url(r'^ListProjet/(?P<NbPage>\d+)$', views.ListProjet, name=''),
    url(r'^login/$', auth_views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),    
)

app/forms/Projet.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from ..models import *
class ProjetForm(forms.ModelForm):
  titre  = forms.CharField(label=_("Nom de la machine"),
                                required=True,max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': "Nom de la machine"})
                               )
  Image = forms.ImageField(required=False,
        label='Choisir une image'
    )
  fichier = forms.FileField(required=False,
        label='Choisir un Fichier'
    )
  Categorie = forms.ModelChoiceField(queryset=(Categorie.objects.all()),
                                      widget=forms.Select(attrs={'class': 'form-control'})
                                      )
  Licence = forms.ModelChoiceField(queryset=(Licences.objects.all()),
                                      widget=forms.Select(attrs={'class': 'form-control'})
                                      )
  Machine = forms.ModelMultipleChoiceField(queryset=(Machine.objects.all()),)
  Materiaux = forms.ModelMultipleChoiceField(queryset=(Matiere.objects.all()),)
  Contenue = forms.CharField(label=_("Descritpion"),
                                required=True,
                               widget=forms.Textarea({
                                   'class': 'form-control',
                                   'placeholder': "Descritpion"}))
  class Meta:
    model = Projet
    fields = ('titre','fichier','Categorie','Image','Licence','Machine','Materiaux','Contenue')

app/forms/register.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class UserCreateForm(UserCreationForm):
    Nom = forms.CharField(label=_("Nom"),
                                required=True,max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': "Nom"}))
    Prenom = forms.CharField(label=_("Prenom"),
                                required=True,max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': "Prenom"}))
    username = forms.CharField(label=_("Nom D'utilisateur"),
                                required=True,max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': "Nom D'utilisateur"}))
    email = forms.EmailField(required=True,max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'email'}))
    password1 = forms.CharField(label=_("Mot de passe"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Mot de passe'}),required=True)
    password2 = password1
    PhoneNumber = forms.CharField(label=_("Numéro de telephone"),
                                required=True,max_length=15,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Numéro de telephone'}))
    NewsLetter = forms.BooleanField(label="Recevoir la newsletter",widget=forms.CheckboxInput({
                                   'class': 'form-control',
                                   } ) )
                                   

app/templates/app/AddProjet.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}
{% load staticfiles %}
<script src="{% static 'app/scripts/tinymce/tinymce.min.js' %}"></script>
<script>tinymce.init({
  selector: 'textarea',
  height: 250,
  theme: 'modern',
  plugins: [
    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
    'searchreplace wordcount visualblocks visualchars code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'emoticons template paste textcolor colorpicker textpattern imagetools'
  ],
  toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  toolbar2: 'print preview media | forecolor backcolor emoticons',
  image_advtab: true,
  content_css: [
    '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
    '//www.tinymce.com/css/codepen.min.css'
  ]
 });
</script>
<link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap-multiselect.css' %}" />
<script src="{% static 'app/scripts/bootstrap-multiselect.js' %}"></script>
<div class="jumbotron">
	{{form.errors}}
	<form action="" method="post" enctype="multipart/form-data">
		<div class="container">
		  <div class="row">
				{% csrf_token %}
				<div class="col-md-9" id="main-content">	
					{% trans "Titre" %} : {{ form.titre }}
							{{ form.Image }}
					{% trans "Description" %} : 
					{{ form.Contenue }}
				</div>
				<div class="col-md-3" id="news">
					<ul class="list-group">
						<li class="list-group-item">{% trans "Categorie" %} : {{ form.Categorie }}</li>
						<li class="list-group-item">{% trans "Licence" %} : {{ form.Licence }}</li>
						<li class="list-group-item">{% trans "Machine" %}e : {{ form.Machine }}</li>
						<li class="list-group-item">{% trans "Materiaux" %} : {{ form.Materiaux }}</li>
						<li class="list-group-item">{% trans "Fichier" %} : {{ form.fichier }}</li>
					</ul>
				</div>
				</br>
			</div>
			<input type="submit" value="Submit" class="btn btn-default"/>
		</div>
	</form>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_Machine').multiselect();
    });
 	$(document).ready(function() {
	$('#id_Materiaux').multiselect();
    });
</script>
{% endblock %}

app/templates/app/DetailArticle.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}
{% load staticfiles %}
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-7" id="main-content">	
				{% if user.is_superuser %}
					<a href="{% url 'admin:app_article_change' data.id %}" class="btn btn-default">{% trans "Edit" %}</a>
				{% endif %}
				
				{{data.Titre}}
				</br>
				{% load static %}
				<img src="{% get_media_prefix %}{{data.Image}}" class="img-responsive" alt="Responsive image" />
				</br>
				{% autoescape off %}
					{{data.Descritpion}}
				{% endautoescape %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/app/DetailAtelier.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}
{% load staticfiles %}
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-7" id="main-content">	
				{% if user.is_superuser %}
					<a href="{% url 'admin:app_atelier_change' data.id %}" class="btn btn-default">{% trans "Edit" %}</a>
				{% endif %}
				
				{{data.Titre}}
				</br>
				{% load static %}
				<img src="{% get_media_prefix %}{{data.Image}}" class="img-responsive" alt="Responsive image" />
				</br>
				{% autoescape off %}
					{{data.Descritpion}}
				{% endautoescape %}
			</div>
			<div class="col-md-5" id="news">
				<ul class="list-group">
					{% load MyTag %}
					{% if  AffichPrix %}
						<li class="list-group-item">{% trans "Tarif" %} : {{data.prix}} €</li>
						<li class="list-group-item">{% trans "TarifAdh" %} : {{data.prixAdh}} €</li>
					{% endif %}
					<li class="list-group-item">{% trans "Date" %} : {{data.date}}</li>
					<li class="list-group-item">{% trans "PlaceRestante" %} : {{nbPlace}}</li>
					{% if user.is_authenticated %}
						{% if depasses %}
							{% if DejaInscrit %}
								<li class="list-group-item"><a href="{% url 'DesinscriptionAtelier' Action=data.id %}" class="btn btn-default">
									{% trans "desInscription" %}</a></li>
							{% else %}
								{% if nbPlace > 0 %}
									<li class="list-group-item"><a href="{% url 'InscriptionAtelier' Action=data.id %}" class="btn btn-default">
									{% trans "Inscription" %}</a></li>
								{% endif %}
							{% endif %}
						{% else %}
							<li class="list-group-item">{% trans "AtelierDepasser" %}</li>
						{% endif %}
					{% else %}
						<li class="list-group-item">{% trans "LogForInsc" %}</li>
					{% endif %}
					{% if user.is_authenticated %}
					<li class="list-group-item"> Inscrit :</li>
						{% for i in inscrit %}
							<li class="list-group-item"> {{i.user.first_name}} {{i.user.last_name}}</li>
						{% endfor %}
					{% endif %}

				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/app/DetailProjet.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}
{% load staticfiles %}

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-7" id="main-content">	
				{{data.titre}}
				{% if user.is_superuser  or user.username == data.Utilisateur.user.username%}
					<a href="{% url 'EditProjet' NbPage=data.id %}" class="btn btn-default">{% trans "Edit" %}</a>
					<a href="{% url 'DeleteProjet' NbPage=data.id %}" class="btn btn-default">{% trans "Suppr" %}</a>
				{% endif %}
				</br>
				{% load static %}
				<img src="{% get_media_prefix %}{{data.Image}}" class="img-responsive" alt="Responsive image" />
				</br>
				{% autoescape off %}
					{{data.Contenue}}
				{% endautoescape %}
			</div>
			<div class="col-md-5" id="news">
				<ul class="list-group">
					<li class="list-group-item">{% trans "Par" %} : {{data.Utilisateur.all.0.user.username}}</li>
					{% if data.fichier %}
						<li class="list-group-item">
							<a href="{% get_media_prefix %}{{data.fichier}}" class="btn btn-default">
								{% trans "Fichier joint" %}
							</a>
						</li>
					{% endif %}
					{% for machine in data.Machine.all %}
					<li class="list-group-item">
						<a href="{% url 'ViewMachine' NbPage=machine.id %}" class="btn btn-default">
							{% trans "Machine" %} : {{machine.Titre}}
						</a>
					</li>
					{% endfor %}
					<li class="list-group-item">{% trans "Categorie" %} : {{ data.Categorie.all.0.Nom }}</li>
					<li class="list-group-item">{% trans "Licence" %} : {{ data.Licence.all.0.Nom }}</li>
					{% for matiere in data.Materiaux.all %}
					<li class="list-group-item">{% trans "Materiaux" %} : {{ matiere.Nom }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>

{% load MyTag %}
<div id="disqus_thread"></div>
	<script>
	    /**
	     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
	     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
	     */
	    
	    var disqus_config = function () {
	        this.page.url = "{{ request.build_absolute_uri }}";  // Replace PAGE_URL with your page's canonical URL variable
	        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	    };
	    
	    (function() {  // DON'T EDIT BELOW THIS LINE
	        var d = document, s = d.createElement('script');
	        
	        s.src = '//{% Infodisqus %}.disqus.com/embed.js';
	        
	        s.setAttribute('data-timestamp', +new Date());
	        (d.head || d.body).appendChild(s);
	    })();
	</script>
	<noscript>
		Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
	</noscript>
</div>
{% endblock %}

app/templates/app/ListArticle.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}	
{% load i18n %}		
<div class="jumbotron">
	<div class="row">
		{% for i in data %}
			<div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			    {% load static %}
			      <img src="{% get_media_prefix %}{{i.Image}}">
			      <div class="caption">
			      	<h3>{{i.Titre}}</h3>
			        <p><a href="{% url 'ViewArticle' NbPage=i.id %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
			      </div>
			    </div>
			  </div>
		{% endfor %}
	</div>
</div>
<ul class="pagination pagination-centered">
	{% if data.has_previous %}
		<li><a href="1"><<</a></li>
		<li><a href="{{ data.previous_page_number }}"><</a></li>
	{% endif %}
	{% for i in nb %}
		<li {% if data.number == i %} class="active" {% endif %}><a href="{{i}}">{{i}}</a></li>
	{% endfor %}
	{% if data.has_next %}
		<li><a href="{{ data.next_page_number }}">></a></li>
		<li><a href="{{ data.paginator.num_pages }}">>></a></li>
	{% endif %}
</ul>
{% endblock %}

app/templates/app/ListAtelier.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}	
{% load i18n %}		
<div class="jumbotron">
	<div class="row">
		{% for i in data %}
			<div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			    {% load static %}
			      <img src="{% get_media_prefix %}{{i.Image}}">
			      <div class="caption">
			      	<h3>{{i.Titre}}</h3>
			      	<h3>{{i.date}}</h3>
			        <p><a href="{% url 'ViewAtelier' NbPage=i.id %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
			      </div>
			    </div>
			  </div>
		{% endfor %}
	</div>
</div>
<ul class="pagination pagination-centered">
	{% if data.has_previous %}
		<li><a href="1"><<</a></li>
		<li><a href="{{ data.previous_page_number }}"><</a></li>
	{% endif %}
	{% for i in nb %}
		<li {% if data.number == i %} class="active" {% endif %}><a href="{{i}}">{{i}}</a></li>
	{% endfor %}
	{% if data.has_next %}
		<li><a href="{{ data.next_page_number }}">></a></li>
		<li><a href="{{ data.paginator.num_pages }}">>></a></li>
	{% endif %}
</ul>
{% endblock %}

app/templates/app/ListMachine.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}		
{% load i18n %}
<div class="jumbotron">
	<div class="row">
		{% for i in data %}
			<div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			    {% load static %}
			      <img src="{% get_media_prefix %}{{i.Image}}" class="img-responsive" alt="Responsive image">
			      <div class="caption">
			        <h3>{{i.Titre}}</h3>
			        <p><a href="{% url 'ViewMachine' NbPage=i.id %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
			      </div>
			    </div>
			  </div>
		{% endfor %}
	</div>
</div>
<ul class="pagination pagination-centered">
	{% if data.has_previous %}
		<li><a href="1"><<</a></li>
		<li><a href="{{ data.previous_page_number }}"><</a></li>
	{% endif %}
	{% for i in nb %}
		<li {% if data.number == i %} class="active" {% endif %}><a href="{{i}}">{{i}}</a></li>
	{% endfor %}
	{% if data.has_next %}
		<li><a href="{{ data.next_page_number }}">></a></li>
		<li><a href="{{ data.paginator.num_pages }}">>></a></li>
	{% endif %}
</ul>
{% endblock %}

app/templates/app/ListProjet.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}
{% load i18n %}		
<div class="jumbotron">
	<form action="" method="get" enctype="multipart/form-data">
		<div class="btn-group btn-group-justified" role="group" >
			<div class="btn-group" role="group">
				<span class="input-group-addon" id="basic-addon1">{% trans "Categorie" %} : {{form.Categorie}} </span>
			</div>
			<div class="btn-group" role="group">
				<span class="input-group-addon" id="basic-addon1">{% trans "Machine" %} : {{form.Machine}} </span>
			</div>
			<div class="btn-group" role="group" >
				<span class="input-group-addon" id="basic-addon1">{% trans "Materiaux" %} : {{form.Materiaux}}</span>
			</div>
		</div>
		<input type="submit" value="{% trans "Recherche" %}" class="btn btn-default"/>
		{% if user.is_authenticated %}
			<a href="{% url 'NewProjet' %}" class="btn btn-default">{% trans "AddProjet" %}</a>
		{% endif %}
	</form>
	<div class="row">
		{% for i in data %}
			<div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			    {% load static %}
			      <img src="{% get_media_prefix %}{{i.Image}}">
			      <div class="caption">
			        <h3>{{i.titre}}</h3>
			        <p><a href="{% url 'ViewProjet' NbPage=i.id %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
			      </div>
			    </div>
			  </div>
		{% endfor %}
	</div>
</div>
<ul class="pagination pagination-centered">
	{% if data.has_previous %}
		<li><a href="1?Categorie={{request.GET.Categorie}}&Materiaux{{request.GET.Materiaux}}=&Machine={{request.GET.Machine}}"><<</a></li>
		<li><a href="{{ data.previous_page_number }}?Categorie={{request.GET.Categorie}}&Materiaux{{request.GET.Materiaux}}=&Machine={{request.GET.Machine}}"><</a></li>
	{% endif %}
	{% for i in nb %}
		<li {% if data.number == i %} class="active" {% endif %}><a 
		href="{{i}}?Categorie={{request.GET.Categorie}}&Materiaux{{request.GET.Materiaux}}=&Machine={{request.GET.Machine}}">{{i}}
		</a></li>
	{% endfor %}
	{% if data.has_next %}
		<li><a href="{{ data.next_page_number }}?Categorie={{request.GET.Categorie}}&Materiaux{{request.GET.Materiaux}}=&Machine={{request.GET.Machine}}">></a></li>
		<li><a href="{{ data.paginator.num_pages }}?Categorie={{request.GET.Categorie}}&Materiaux{{request.GET.Materiaux}}=&Machine={{request.GET.Machine}}">>></a></li>
	{% endif %}
</ul>
{% endblock %}

app/templates/app/Profil.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}	
{% load i18n %}		
<div class="jumbotron">
<a href="{% url 'EditNewsLetter' %}" class="btn btn-default">
	{% if NewsLetter %}
		{% trans "Desactiver NewsLetter" %}
	{% else %}
		{% trans "Activer NewsLetter" %}
	{%endif%}
</a>
	</br>
	{% trans "Mes Projet :" %}
	<div class="row">
		{% for i in Projet %}
			<div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			    {% load static %}
			      <img src="{% get_media_prefix %}{{i.Image}}">
			      <div class="caption">
			      	<h3>{{i.Titre}}</h3>
			      	<h3>{{i.date}}</h3>
			        <p><a href="{% url 'ViewAtelier' NbPage=i.id %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
			      </div>
			    </div>
			  </div>
		{% endfor %}
	</div>
	{% trans "Mes Atelier :" %}
	<div class="row">
		{% for i in Evenement %}
			<div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			    {% load static %}
			      <img src="{% get_media_prefix %}{{i.Image}}">
			      <div class="caption">
			        <h3>{{i.titre}}</h3>
			        <p><a href="{% url 'ViewProjet' NbPage=i.id %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
			      </div>
			    </div>
			  </div>
		{% endfor %}
	</div>
</div>
{% endblock %}

app/templates/app/about.html
{% extends "app/layout.html" %}
{% block content %}
{% load i18n %}	
<h2>{{ title }}.</h2>

<p>{% trans "about" %}	</p>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}
{% load i18n %}
<div class="jumbotron">
	<div class="row">
		<div class="col-sm-1000 col-md-4">
			<div class="thumbnail">
				{% load static %}
				{% if LastProject != None %}
					<img src="{% get_media_prefix %}{{LastProject.Image}}" class="img-responsive" alt="Responsive image" />
				{% else %}
					<img src="{% static 'app/Image/no_avatar.png' %} " class="img-responsive" alt="Responsive image"/>
				{% endif %}
				<div class="caption">
					<h3>{% trans "Dernier projet" %}</h3>
			        <p><a href  ="{% url 'ListProjet' %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				{% load static %}
				{% if LastEvent != None %}
					<img src="{% get_media_prefix %}{{LastEvent.Image}}" class="img-responsive" alt="Responsive image"/>
				{% else %}
					<img src="{% static 'app/Image/no_avatar.png' %} " class="img-responsive" alt="Responsive image"/>
				{% endif %}
				<div class="caption">
					<h3>{% trans "Liste des ateliers" %}</h3>
			        <p><a href  ="{% url 'ListAtelier' %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				{% load static %}
				{% if LastMachine != None %}
					<img src="{% get_media_prefix %}{{LastMachine.Image}}" class="img-responsive" alt="Responsive image"/>
				{% else %}
					<img src="{% static 'app/Image/no_avatar.png' %} " class="img-responsive" alt="Responsive image"/>
				{% endif %}
				<div class="caption">
					<h3>{% trans "Liste des machines" %}</h3>
			        <p><a href  ="{% url 'ListMachine' %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
				</div>
			</div>
		</div>
	</div>
{% if LastArticle %}
	<h3>{% trans "Dernier Article Publier : " %}</h3>
	<div class="row">
			{% for i in LastArticle %}
			<div class="col-sm-6 col-md-4">
			    <div class="thumbnail">
			    {% load static %}
			      <img src="{% get_media_prefix %}{{i.Image}}">
			      <div class="caption">
			      	<h3>{{i.Titre}}</h3>
			        <p><a href="{% url 'ViewArticle' NbPage=i.id %}" class="btn btn-primary" role="button">{% trans "Consulter" %}</a> 
			      </div>
			    </div>
			  </div>
		{% endfor %}
	</div>
{%endif%}
</div>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="" method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>{% trans "USeLocalLogin" %}</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">{% trans "UserName" %}</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">{% trans "Mdp" %}</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">{% trans "PleaseCorrectUser" %}</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}